In [1]:
import numpy as np

a  = np.matrix('1,2,3;4,5,6')
b = np.array([[1,2,3],[4,5,6]])

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [3]:
c = np.arange(6)
print(c)

[0 1 2 3 4 5]


In [4]:
import random as rd
def array_generator(m):
    x = []
    for i in range(m):
        x.append(rd.randint(0,10))
    return x

def matrix_generator(r,c):
    x = []
    for i in range(r*c):
        x.append(rd.randint(0,10))
    

w = array_generator(5)
x = array_generator(5)
y = array_generator(5)
z = array_generator(5)

d = np.array([w,x,y,z])

e = np.array([np.arange(1,6),np.arange(6,11),np.arange(11,16),np.arange(16,21)])

f = matrix_generator(2,3)
print(d)
print()
print(e)
print()
print(f)

[[ 7  3  5  0  3]
 [ 9  5  2  7  7]
 [ 0 10  9  7  4]
 [ 3  4  9  5  7]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

None


# Order of the  matrix

In [5]:
print(a.shape)
print(b.shape)


(2, 3)
(2, 3)


## Matrix addition

In [6]:


a = np.matrix('1 1;2 43')
b = np.matrix('1 4;1 32')

print(f'a + b = \n{a+b}')

a + b = 
[[ 2  5]
 [ 3 75]]


## Matrix Scalar multiplications

In [7]:
a = np.array([[1,5,7],[4,7,23]])
a4 = a * 4
print(a4)

[[ 4 20 28]
 [16 28 92]]


# Matrix Mul

In [8]:
mul1 = np.matrix('1 4 6;2 7 3')
mul2 = np.matrix('2 5;6 8;2 4')

mul3 = np.array([[1,4,6],[2,7,3]])
mul4 = np.array([[2,5],[6,8],[2,4]])

ans = mul1 * mul2 # for matrix created with matrix function this will work
ans2 = mul3.dot(mul4) # for matrix created with arrays .dot() should be used
print(ans)
print(ans2)

[[38 61]
 [52 78]]
[[38 61]
 [52 78]]


## Transpose of a matrix

In [ ]:
at = np.array([[1,7,43],[9,2,4]])
at_transpose = np.matrix.transpose(at)

print(at)
print()
print(at_transpose)

[[ 1  7 43]
 [ 9  2  4]]

[[ 1  9]
 [ 7  2]
 [43  4]]


array([[ 1,  7, 43],
       [ 9,  2,  4]])

In [9]:
import sympy as sp
from sympy import *

A =  Matrix([[0,2],[3,6]])
B = Matrix([[4,7],[3,9]])

A+B
    

Matrix([
[4,  9],
[6, 15]])

In [ ]:
A-B

Matrix([
[-4, -5],
[ 0, -3]])

In [ ]:
A * B

Matrix([
[ 6, 18],
[30, 75]])

In [ ]:
C = transpose(A)
C


Matrix([
[0, 3],
[2, 6]])

## Inverse of a matrix

In [ ]:
x1 = [1,2,3]
x2 = [4.5,6]
x3 = [7,8,9]

a = np.matrix('1 2 5;0 8 0;7 6 1')

x = np.linalg.inv(a)

print(x)
print(y)

[[-0.02941176 -0.10294118  0.14705882]
 [ 0.          0.125       0.        ]
 [ 0.20588235 -0.02941176 -0.02941176]]
-271.9999999999999


## Determination of a matrix

In [ ]:
x1 = [1,2,3]
x2 = [4.5,6]
x3 = [7,8,9]

a = np.matrix('1 2 5;0 8 0;7 6 1')

y = np.linalg.det(a)

print(x)
print(y)

## Soving equations with matrix

In [ ]:
ax = np.matrix('3 -1 1;2 1 0;1 2 -1')
bx = np.matrix('2;1;3')

c = np.linalg.solve(ax,bx)

print(c)

[[ 2.]
 [-3.]
 [-7.]]


## Inverse and Deteminant using numpy

In [ ]:
import numpy as np
x1 = [1,2,3]
x2 = [4.5,6]
x3 = [7,8,9]

a = np.matrix('1 2 5;0 8 0;7 6 1')

x = np.linalg.inv(a)
y = np.linalg.det(a)

print(x)
print(y)