In [4]:
import numpy as np
A = np.matrix('1 2 3 4;5 6 7 8;9 10 11 12; 13 14 15 16')
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

C = A[0:2,2:4]
D = B[1:5,1:5]
print(C)
print(D)

[[3 4]
 [7 8]]
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [13]:

E = np.matrix('3 4 7;2 4 5')
H = np.matrix('1 2 3;4 5 6')
I = np.matrix('2 3;1 4;5 6')

print(E+H)
print(E-H)
print(3 * H)
print(H * I)

[[ 4  6 10]
 [ 6  9 11]]
[[ 2  2  4]
 [-2 -1 -1]]
[[ 3  6  9]
 [12 15 18]]
[[19 29]
 [43 68]]


In [24]:
print(np.linalg.det(H * I))
print(np.linalg.inv(H * I))
print(np.transpose(I))



44.99999999999999
[[ 1.51111111 -0.64444444]
 [-0.95555556  0.42222222]]
[[2 1 5]
 [3 4 6]]


In [26]:
SolveA = np.matrix('3 2 3;2 1 -1;4 2 -3')
solveB = np.matrix('2;6;7')

np.linalg.solve(SolveA,solveB)

matrix([[ 35.],
        [-59.],
        [  5.]])