## Vectors

In [1]:
import numpy as np

lst1 = [10,20,30,40,50]

vector1 = np.array(lst1)

print(f'Vector Created from a list : {vector1}')

Vector Created from a list : [10 20 30 40 50]


In [2]:
lst2 = [[1],[2],[3],[4],[5]]

vector2 = np.array(lst2)

print(f'This is also a Vector: {vector2}')

This is also a Vector: [[1]
 [2]
 [3]
 [4]
 [5]]


## Adding 2 Vectors

In [3]:
vctr1 = np.array([1,4,6,32,6])
vctr2 = np.array([4,23,7,2,6])

c = vctr1 + vctr2
print(f'addition of two vectors = {c}')

addition of two vectors = [ 5 27 13 34 12]


## Vector Divison 

In [17]:
vctr1 = np.array([1,4,6,32,6])
vctr2 = np.array([4,23,7,2,6])

vctr_div = vctr1 / vctr2
print(f'Devided vector : {vctr_div}')

Devided vector : [ 0.25        0.17391304  0.85714286 16.          1.        ]


## Magnitude of a vector

In [22]:
# Method 1 : Using norm() in linalg (linear algebra)

x = np.array([4,7,3,4,8,3,9])

mag_of_x = np.linalg.norm(x)
print(f'Magnitude of vector in method 1 {x} ==> {mag_of_x}')

# Method 2 : Using the dot product
mag_x_2 = np.sqrt(x.dot(x))
print(f'Magnitude of vector in method 2 {x} ==> {mag_x_2}')
# Method 3 : Using the np.dot product
mag_x_3 = np.sqrt(np.dot(x,x))
print(f'Magnitude of vector in method 3 {x} ==> {mag_x_3}')


Magnitude of vector in method 1 [4 7 3 4 8 3 9] ==> 15.620499351813308
Magnitude of vector in method 2 [4 7 3 4 8 3 9] ==> 15.620499351813308
Magnitude of vector in method 3 [4 7 3 4 8 3 9] ==> 15.620499351813308


# Unit Vector

In [6]:
# Method 1 : Using unit_vector() in transformations library

import transformations as tr

vctrx = np.array([1,2,3])

u_vctrx = tr.unit_vector(vctrx)
print(f'Unit Vector of vector {vctrx} is: {u_vctrx[0:1][0]}i + {str(u_vctrx[1:2][0])}j + {u_vctrx[2:3][0]}k {u_vctrx}')

Unit Vector of vector [1 2 3] is: 0.2672612419124244i + 0.5345224838248488j + 0.8017837257372732k [0.26726124 0.53452248 0.80178373]


# Finding Eigen Values

In [5]:
import numpy as np
A = np.array([[1,0,-1],[1,2,1],[2,2,3]])

c,d = np.linalg.eig(A)

e = np.linalg.inv(d)
print(c)
print(e)


[2. 3. 1.]
[[-3.00000000e+00 -3.00000000e+00 -3.16413562e-15]
 [ 2.44948974e+00  2.44948974e+00  1.22474487e+00]
 [-0.00000000e+00 -1.41421356e+00  7.07106781e-01]]
